### ISSUE TITLE
Advice on removing Avahi/Samba from the host

### ISSUE THREAD

**Issue by maxim** [mbentley/docker-timemachine#123]
Disclaimer: apologies for using Feature template to ask a question. Readme seems to welcome it (search readme for the word "assist").

### What problem are you looking to solve?

I have avahi and samba running on the host. Since I installed them via `apt install` on Ubuntu 18.04, they are quite outdated. They only do 2 things:

1. Share one dir.
2. Provide a .local domain for the host machine.

I'd like to figure out the best way to add this docker image to my setup.

### Describe the solution that you have in mind

Would it make sense to remove avahi and samba from host, and use the ones in this image for dir sharing, .local domain, and Time Machine (all 3)? Does this image allow for configuring extra stuff such as this?

Or would you say it's better to embrace avahi/samba on the host (I can find a way to update them), and use macvlan or reflector approach?

What would in your opinion be the path of least resistance?

### Additional Context

Appreciate your work on this!

**Comment by mbentley** [comment]
Sorry that I wasn't able to reply sooner.  The image isn't really geared toward managing more than just time machine but it is certainly possible if you generate your own Samba config.  You can run the container, copy out the config and then add your own customizations but it has been quite a while since some of the more advanced features were added to the image so I would have to re-figured out how things like additional custom users and whatnot would work.  It's absolutely feasible but there would be a bit of work to get it working fully.

**Comment by maxim** [comment]
Thanks Matt, appreciate the response, no worries about the delay. I've gone a different direction since, but hopefully this clears things up for someone looking to do the same thing.
