### ISSUE TITLE
Multiple volumes support

### ISSUE THREAD

**Issue by hryamzik** [mbentley/docker-timemachine#18]
Is there a way to share multiple volumes?

Looks like running multiple containers on `--host` mode won't work so the trivial option could be using a network bridge. At this point multi-volume support seem to be a less overhead.

**Comment by mbentley** [comment]
It would probably be easiest if you either extended this Docker image or added a custom `afp.conf`
using the `CUSTOM_AFP_CONF` env var, depending on what you need.  A custom `afp.conf` is pretty basic:  https://github.com/mbentley/docker-timemachine/blob/master/entrypoint.sh#L76-L87.  If you need to add multiple users, then that would be a different story as you'd have to create the user accounts as currently the entrypoint only handles one account.  I'd have to understand exactly what you're trying to achieve to be able to solve for it but it should be doable

**Comment by hryamzik** [comment]
My idea is to have multiple shares for multiple laptops.

**Comment by mbentley** [comment]
Do you require different users?  If not, then I would just use the ability to bind mount a custom afp.conf with multiple shares, using the same user account.  Maybe give that a shot to see if that works for you use case.

**Comment by hryamzik** [comment]
Multiple users would be nice but not required. Got it, I'll play with `afp.conf`, ty!

**Comment by mbentley** [comment]
Sure thing.  Let me know if that works.   If it does and you still need multiple users, I will see what I can do to add an ability to loop through adding multiple users.

**Comment by tmc975** [comment]
i would also vote for multiple users/shares solution where you could also configure different quota per user. Otherwise one computer/user can fill all space with backup while other computers/users also need space :-) Had similar configuration on Synology and worked well.

Few more ideas:
- would be great to have different network configurations ready. You may want to run several  afp/smb docker's in your infra and then it could be handy up front. 
- hostname setting ;) if you don't use network mode 'host' then ... technical hostname shows up :-)

**Comment by mbentley** [comment]
Maybe I will see if I can figure out some sort of sane way to pass in multiple values for multiple shares.  It basically means I need to be able to parse out the env vars for `SHARE_NAME`, `VOLUME_SIZE_LIMIT`, `TM_USERNAME`, `PASSWORD`, `TM_GROUPNAME`, `TM_UID`, `TM_GID` and then also some loops to make it all happen.  I need to figure out something I can use the delimit the multiple parameters or maybe even just have it so that you could append a number to each of the above variables (e.g. - `SHARE_NAME_2`, `SHARE_NAME_3`) and figure out a way to pick those up (I haven't taken that approach with any other entrypoints before so I don't have any existing code to start from).

**Comment by tmc975** [comment]
about shares - idea separated N amount files for each share is most simple way ? by default there is one and you can add as many as you need and read them in with foreach ?

about macvlan - can you share your conf ? Im newbie in that area and i had quite big hassle with it because when i created two machines in same network space - i had problem. so i have to share same network between them. but if one machine is down then how you automatically create shared network ? ps, Im tryng to use only docker-compose.yml and i try avoid creating anything manually. not sure - is it even possible or reasonable way.

**Comment by mbentley** [comment]
Yeah, I'm just trying to figure out what would be the cleanest implementation.  I hate creating extra dependencies like having a file.

Sure here is my config:

Create a macvlan network where you specify the parameters of your actual network you're on:
```
docker network create -d macvlan --subnet=192.168.0.0/24 --gateway=192.168.0.1 -o parent=eth0 macvlan1
```

Create the `timemachine1` container using the macvlan1 network you just created.  Assign a "static" IP otherwise Docker will just pick an IP which you don't want:
```
docker run -d \
  --restart=always \
  --name timemachine1 \
  --hostname timemachine1 \
  --network macvlan1 \
  --ip 192.168.0.51 \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="true" \
  -e SHARE_NAME="TimeMachine" \
  -e VOLUME_SIZE_LIMIT="1 T" \
  -e WORKGROUP="timemachine" \
  --mount type=bind,source=/zfs/storage/timemachine1,destination=/opt/timemachine,readonly=false \
  --mount type=volume,source=timemachine1-var-log,destination=/var/log,readonly=false \
  --mount type=volume,source=timemachine1-var-lib-samba,destination=/var/lib/samba,readonly=false \
  --mount type=volume,source=timemachine1-var-cache-samba,destination=/var/cache/samba,readonly=false \
  --mount type=volume,source=timemachine1-run-samba,destination=/run/samba,readonly=false \
  --cpus 2 \
  --memory 2g \
  --memory-swap 3g \
  mbentley/timemachine:smb
```

If I wanted to run another as `timemachine2`:
```
docker run -d \
  --restart=always \
  --name timemachine2 \
  --hostname timemachine2 \
  --network macvlan1 \
  --ip 192.168.0.52 \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="true" \
  -e SHARE_NAME="TimeMachine" \
  -e VOLUME_SIZE_LIMIT="1 T" \
  -e WORKGROUP="timemachine" \
  --mount type=bind,source=/zfs/storage/timemachine2,destination=/opt/timemachine,readonly=false \
  --mount type=volume,source=timemachine2-var-log,destination=/var/log,readonly=false \
  --mount type=volume,source=timemachine2-var-lib-samba,destination=/var/lib/samba,readonly=false \
  --mount type=volume,source=timemachine2-var-cache-samba,destination=/var/cache/samba,readonly=false \
  --mount type=volume,source=timemachine2-run-samba,destination=/run/samba,readonly=false \
  --cpus 2 \
  --memory 2g \
  --memory-swap 3g \
  mbentley/timemachine:smb
```

**Comment by mbentley** [comment]
And just a little proof of concept with multiple variables:

```
#!/bin/sh

#set -x

export TM_USERNAME="foo"
export TM_USERNAME_2="bar"
export TM_USERNAME_3="baz"

for USER_VAR in $(env | grep '^TM_USERNAME')
do
  echo "${USER_VAR}" | awk -F '=' '{print $2}'
done
```

```
# ./test.sh
bar
baz
foo
```

**Comment by tmc975** [comment]
thanks for macvlan example. i'll stop finding a way to create it automatically and just use manually too then :-)

about arrays and files - i agree, it would look better if you could use arrays and even better - multilevel arrays, because there are to many parameters per user.  Dirty way would be exploring complex strings, alternative would be shift away from /bin/sh. But i still feel that if you want to have full flexibility per configuration, i think separated files would look better... and you could combine it in configuration like - if you use single user, then config is from here or else EXTENDED_CONFIGURATION=true or smth ?

**Comment by mbentley** [comment]
It would be a lot of refactoring because of how the current entrypoint is built right now but I could designate a special character to separate the values like `:` (which this would mean you couldn't use `:` in any passwords but it might be an acceptable compromise.

```
#!/bin/sh

export SHARE_NAME="foo:bar:baz"
export VOLUME_SIZE_LIMIT="1 T:512 M:256 M"
export TM_USERNAME="foo:bar:baz"
export PASSWORD="foopass:barpass:bazpass"
export TM_GROUPNAME="foogroup:bargroup:bazgroup"
export TM_UID="1000:1001:1002"
export TM_GID="1000:1001:1002"

# get number of values provided
LENGTH="$(echo "${TM_USERNAME}" | awk -F ':' '{print NF}')

get_value() {
  echo "${2}" | awk -F ':' '{print $'"${1}"'}'
}

for i in $(seq 1 "${LENGTH}")
do
  get_value "${i}" "${TM_USERNAME}"
  get_value "${i}" "${TM_GROUPNAME}"
  get_value "${i}" "${PASSWORD}"
  get_value "${i}" "${SHARE_NAME}"
  get_value "${i}" "${VOLUME_SIZE_LIMIT}"
  get_value "${i}" "${TM_UID}"
  get_value "${i}" "${TM_GID}"
  echo
done
```
```
# ./test2.sh
foo
foogroup
foopass
foo
1 T
1000
1000

bar
bargroup
barpass
bar
512 M
1001
1001

baz
bazgroup
bazpass
baz
256 M
1002
1002
```

```

**Comment by tmc975** [comment]
mhm, this works until you have two or three users. I mean - it's countable. But if you have small office like 20 and you want to change object 13 ? :-)

**Comment by mbentley** [comment]
Yeah, I was actually going to ask what sort of number of users might this even be used for.  That does become quite a pain in the ass to maintain that list and leaves too much room for error.

**Comment by tmc975** [comment]
but im wondering - if you would continue this EXTERNAL_CONF idea. I imagine it like this:

by default - current way is used
if conf_files=true then current values are used as defaults for each file what does not have some parameter set. for example if you don't want to define different quota for each user.

it would not complicate current setup and at same time - it's readable and it's quite easy to implement ?

**Comment by mbentley** [comment]
Yeah, it certainly makes much more sense in that context.  Were you thinking something like this would work where each file is a specific user and I could just loop through each file?

foo
```
TM_USERNAME=foo
TM_GROUPNAME=foogroup
PASSWORD=foopass
SHARE_NAME=foo
VOLUME_SIZE_LIMIT=1 T
TM_UID=1000
TM_GID=1000
```

bar
```
TM_USERNAME=bar
TM_GROUPNAME=bargroup
PASSWORD=barpass
SHARE_NAME=bar
VOLUME_SIZE_LIMIT=512 M
TM_UID=1001
TM_GID=1001
```

baz
```
TM_USERNAME=baz
TM_GROUPNAME=bazgroup
PASSWORD=bazpass
SHARE_NAME=baz
VOLUME_SIZE_LIMIT=256 M
TM_UID=1002
TM_GID=1002
```

**Comment by tmc975** [comment]
mhm, makes sense to me

**Comment by tmc975** [comment]
ps, volume_size_limit = quota ? :-) smaller names do look better

**Comment by mbentley** [comment]
I'll have to see if I can put something together today and see how that goes.

**Comment by mbentley** [comment]
I originally called it `VOLUME_SIZE_LIMIT` because that is what it is called in when using AFP: https://github.com/mbentley/docker-timemachine/blob/4b8056f72bdaa8eff6a20b8128fbabb5852fa721/entrypoint.sh#L232

**Comment by tmc975** [comment]
ok, then it makes sense :-)

**Comment by mbentley** [comment]
OK, I have a branch with the feature added: https://github.com/mbentley/docker-timemachine/tree/smb-multiple-users.  I added it only for SMB because I do not want to support AFP long term.

Take a look at the example for the new variable `EXTERNAL_CONF` and the file format.  I pushed a docker tag that can be tested as `mbentley/timemachine:smb-pr21`.  Let me know what you think about that from a usability standpoint.

My run command:

```
docker run -it --rm \
  --name timemachine \
  -e CUSTOM_SMB_CONF="false" \
  -e CUSTOM_USER="false" \
  -e EXTERNAL_CONF="/users" \
  -e MIMIC_MODEL="TimeCapsule8,119" \
  -e TM_USERNAME="timemachine" \
  -e TM_GROUPNAME="timemachine" \
  -e TM_UID="1000" \
  -e TM_GID="1000" \
  -e PASSWORD="timemachine" \
  -e SET_PERMISSIONS="false" \
  -e SHARE_NAME="TimeMachine" \
  -e VOLUME_SIZE_LIMIT="0" \
  -e WORKGROUP="WORKGROUP" \
  -v timemachine:/opt/timemachine \
  -v timemachine-var-log:/var/log \
  -v timemachine-var-lib-samba:/var/lib/samba \
  -v timemachine-var-cache-samba:/var/cache/samba \
  -v timemachine-run-samba:/run/samba \
  -v $HOME/users:/users \
  mbentley/timemachine:smb-pr21
```

Output from the container:
```
INFO: CUSTOM_SMB_CONF=false; generating [global] section of /etc/samba/smb.conf...
INFO: Loading values from /users/bar
INFO: Group doesn't exist; creating...
INFO: User doesn't exist; creating...
INFO: Setting password from environment variable
chpasswd: password for 'bar' changed
INFO: CUSTOM_SMB_CONF=false; generating [bar] section of /etc/samba/smb.conf...
User bar password set to none.
Enabled user bar.
INFO: Loading values from /users/baz
INFO: Group doesn't exist; creating...
INFO: User doesn't exist; creating...
INFO: Setting password from environment variable
chpasswd: password for 'baz' changed
INFO: CUSTOM_SMB_CONF=false; generating [baz] section of /etc/samba/smb.conf...
User baz password set to none.
Enabled user baz.
INFO: Loading values from /users/foo
INFO: Group doesn't exist; creating...
INFO: User doesn't exist; creating...
INFO: Setting password from environment variable
chpasswd: password for 'foo' changed
INFO: CUSTOM_SMB_CONF=false; generating [foo] section of /etc/samba/smb.conf...
User foo password set to none.
Enabled user foo.
INFO: SET_PERMISSIONS=false; not setting ownership and permissions
2020-01-22 14:57:37,270 INFO Set uid to user 0 succeeded
2020-01-22 14:57:37,281 INFO supervisord started with pid 1
2020-01-22 14:57:38,251 INFO spawned: 'dbus' with pid 50
2020-01-22 14:57:38,258 INFO spawned: 'avahi' with pid 51
2020-01-22 14:57:38,264 INFO spawned: 'nmbd' with pid 52
2020-01-22 14:57:38,268 INFO spawned: 'smbd' with pid 53
2020-01-22 14:57:40,214 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-22 14:57:40,214 INFO success: avahi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-22 14:57:40,215 INFO success: nmbd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-22 14:57:40,215 INFO success: smbd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

The generated `smb.conf` from the container:
```
[global]
   server role = standalone server
   workgroup = WORKGROUP
   unix password sync = yes
   log file = /var/log/samba/log.%m
   logging = file
   max log size = 1000
   security = user
   load printers = no
   fruit:model = TimeCapsule8,119

[bar]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 512 M
   path = /opt/bar
   valid users = bar
   browseable = yes
   writable = yes
   vfs objects = catia fruit streams_xattr

[baz]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 256 M
   path = /opt/baz
   valid users = baz
   browseable = yes
   writable = yes
   vfs objects = catia fruit streams_xattr

[foo]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 1 T
   path = /opt/foo
   valid users = foo
   browseable = yes
   writable = yes
   vfs objects = catia fruit streams_xattr
```

**Comment by mbentley** [comment]
If that makes sense, I will have to add in error checking for each variable to make sure it is defined.

**Comment by tmc975** [comment]
looks great at first sight but somewhy i didn't get it working yet :-) sure, had not much time for debug either. probably my fault somewhere:

@docker docker/samba# docker exec -it timemachine sh
/ # ls /users
conf1  conf2
/ # echo $EXTERNAL_CONF
/users
/ # cat /etc/samba/smb.conf 
[global]
   server role = standalone server
   workgroup = WORKGROUP
   unix password sync = yes
   log file = /var/log/samba/log.%m
   logging = file
   max log size = 1000
   security = user
   load printers = no
   fruit:model = TimeCapsule8,109

[TimeMachine]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 0
   path = /opt/timemachine
   valid users = timemachine
   browseable = yes
   writable = yes
   vfs objects = catia fruit streams_xattr
/ # 



====


$ cat docker-compose.yml
version: '3'
services:
  timemachine:
    networks:
      macvlan1:
        ipv4_address: 192.168.1.7
    environment:
      - CUSTOM_AFP_CONF=false
      - CUSTOM_USER=false
      - EXTERNAL_CONF=/users
      - LOG_LEVEL=info
      - MIMIC_MODEL=TimeCapsule8,109
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=true
      - SHARE_NAME=TimeMachine
      - VOLUME_SIZE_LIMIT=0
    restart: unless-stopped
    ports:
     - "548:548"
     - "636:636"
    volumes:
     - /mnt/sdb1/timemachine:/opt/timemachine
     - ./timemachine-netatalk:/var/netatalk
     - ./timemachine-logs:/var/log/supervisor
     - ./users:/users:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:smb

networks:
  macvlan1:
    external: true

**Comment by mbentley** [comment]
Your compose file is pointing to the wrong image tag.  I pushed a temporary tag to Docker Hub.

`image: mbentley/timemachine:smb`  should be `image: mbentley/timemachine:smb-pr21`

**Comment by tmc975** [comment]
good point, works;) 

ps configuration of samba should be also tweaked i think. Currently all shares are exposed to all users. Sure, you can't get int but you should not know that other user has also share ;)

pps, so far i had heard that samba does not fit for timemachine but seems it wasn't about samba... cool :-)

**Comment by mbentley** [comment]
Ah great point!  I just pushed https://github.com/mbentley/docker-timemachine/pull/21/commits/08359544c3c021cf27f9eb581c8bdad96c7e2c38 which adds an environment variables `HIDE_SHARES` that defaults to `no` but can be set to `yes` in order to hide shares a user doesn't have access to.

 I also re-pushed the same test image tag if you really want to see but here are the results when logged in as user `foo`:

Set to `no`:
![screenshot 2020-01-22 at 12 33 41 PM](https://user-images.githubusercontent.com/414445/72918342-826bd780-3d13-11ea-904f-529f11801e0e.png)

Set to `yes`:
![screenshot 2020-01-22 at 12 33 19 PM](https://user-images.githubusercontent.com/414445/72918343-826bd780-3d13-11ea-92a2-848fab6231f3.png)

**Comment by tmc975** [comment]
awesome 👍

**Comment by mbentley** [comment]
Good deal.  I'm going to go ahead and merge this so I can get it built.
