### ISSUE TITLE
ready-start for smb + few more ideas

### ISSUE THREAD

**Issue by tmc975** [mbentley/docker-timemachine#22]
just wondering, maybe makes sense to organize files and give easier start with smb ?

mv timemachine-compose.yml docker-compose.afp
cp docker-compose.afp docker-compose.smb
vi docker-compose.smb // fix some things, like image...
ln -s docker-compose.yml docker-compose.afp [as current default]

and in README you can point either symlink thisway or otherway. Example inspired by current Dockerfile example in this dir.

ps, 
1. after using /user mount for generating configurations, would be great to remove it from live instance. Security reasons, common standard or smth.
2. HIDE_SHARES - you might turn on it by default, it's something you can turn around anytime but you don't want to have it on by default on timemachine anyways.
3. ignore filename~, .hidden files, .swp and etc tmp files in custom-users files. maybe some certain pattern would be safer ? name.conf or smth ?
4. not configured params - tested, you still need to configure all fields for every account separated. but makes sense to generate UID and GID but in samba conf force reads-writes with certain UID/GID. specially from HOST specific cases in timemachine perspective. Otherwise it might mess up master storage drive and it's easier configure if you dont have copy-paste them to all files. i do remember that samba had special parameters for that...

update:
   force user = ...
   force group = ...
specify for each share

**Comment by mbentley** [comment]
I haven't forgotten about this; I'll have to take a look at implementing some of your suggestions when I have some more time.

**Comment by mbentley** [comment]
I implemented the updates to the compose file to be a symlink.

1. Currently, the user defined files are still needed when you re-launch the container as the entrypoint will actually re-write the smbd.service for Avahi and also the `smb.conf` for Samba.  This allows to adding new users to be added and I struggle with changing defaults after they already exist, especially for a Docker image which seems to be in use fairly widely.
2. Since it can be toggled the other way and it currently is the default to `off`, I am not sure I want to change the default with it as is in the wild.
3. I just added a change to make it only look for `*.conf` files as that makes sense to me.
4. Not sure if that is required - what issues are you seeing there?  Each user should only be able to write to their own directory.  I haven't specifically seen any Time Machine related documentation require the `force` parameters.  Is there anything you could point me to on that?

PR #36 addresses the above changes.
