### ISSUE TITLE
Rounding issues with free space

### ISSUE THREAD

**Issue by utdrmac** [mbentley/docker-timemachine#7]
I created a partition on my NAS for TM backups.
```
/dev/mapper/bigstorage--vg-timemachine  250G   15G  236G   6% /opt/timemachine
```

Then I launched the docker with the following:
```
-e VOLUME_SIZE_LIMIT="250000"
```

When I add the disk to TM on the mac, it says "247 GB of 262 GB available". Where is the rounding/math error? If I set VOLUME_SIZE_LIMIT to 0, then TM on mac says "Zero GB of --- available". Is that correct? If I set to 0, will it default limit to size of partition?

**Comment by mbentley** [comment]
I am not sure about how it calculates the size but the default for `VOLUME_SIZE_LIMIT` is `0` which will default to having no limit.  I am not sure what that does for time machine's ability to intelligently remove old backup files as needed.  My assumption would be that it would detect the size of the volume and use that for the backup but from what you're saying, it might not be able to.  Could be something to do with the format of the partition.  What did you format it as?  I believe on my ext4 partition, it was previously able to detect the whole disk size.  I have mine set to `1012000` which reports `1.06 TB` in the Time Machine UI on my Mac.

Per the [afp.conf documentation](http://netatalk.sourceforge.net/3.0/htmldocs/afp.conf.5.html), the value is in `MiB` which is actually 1 MB = 1.04858 MB.  So that is where it is getting 250000 = 262145 (or 262 GB).  So 250 GB would be 238419 MiB.  Try setting it to that and it should show ~250 GB in Time Machine.

**Comment by utdrmac** [comment]
That made the difference. Thanks!

**Comment by utdrmac** [comment]
Maybe add a note to the README that VOLUME_SIZE is in Mebibytes?

**Comment by mbentley** [comment]
Good call.  Done via #8
