### ISSUE TITLE
How to add additional shares , and access it with same user "timemachine"

### ISSUE THREAD

**Issue by i-zhaopin** [mbentley/docker-timemachine#73]
I add a new share path "mnt". 
and I want to access it with user "timemachine".
but it seems I can only access it with user "mnt".

- /etc/samba/smb.conf
```
[mnt]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 1 T
   fruit:nfs_aces = yes
   path = /opt/mnt
   inherit permissions = no
   valid users = mnt timemachine  *******
   browseable = yes
   writable = yes
   vfs objects = acl_xattr fruit streams_xattr

[timemachine]
   fruit:aapl = yes
   fruit:time machine = yes
   fruit:time machine max size = 300 G
   fruit:nfs_aces = yes
   path = /opt/timemachine
   inherit permissions = no
   valid users = timemachine
   browseable = yes
   writable = yes
   vfs objects = acl_xattr fruit streams_xattr
```

**Comment by mbentley** [comment]
I could have sworn that I replied to this but apparently not.  I manually tested by execing in, changing the config by creating a new directory, adding the new share to the smb.conf, killing the samba processes to force it to restart samba and I was able to connect to and write to the share as expected.

I just don't have an automated way to create multiple shares as a part of the entrypoint in the image.  Due to some legacy behavior, it would be a bit messy.  It might be easier to use the external config options if you need to have separate shares.  You can use multiple machines backing up to the same share - they'll put backups in their own directories.

**Comment by hollie** [comment]
Hey @i-zhaopin for your reference I have setup what you want by using a custom `smb.conf` file like this:

```
[global]
   access based share enum = no
   hide unreadable = no
   inherit permissions = no
   load printers = no
   log file = /var/log/samba/log.%m
   logging = file
   max log size = 1000
   security = user
   server min protocol = SMB2
   server role = standalone server
   smb ports = 445
   workgroup = WORKGROUP
   vfs objects = acl_xattr fruit streams_xattr
   fruit:aapl = yes
   fruit:nfs_aces = yes
   fruit:model = TimeCapsule8,119
   fruit:metadata = stream
   fruit:veto_appledouble = no
   fruit:posix_rename = yes
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes

[mars]
   path = /opt/mars
   inherit permissions = no
   read only = no
   valid users = timemachine
   vfs objects = acl_xattr fruit streams_xattr
   fruit:time machine = yes
   fruit:time machine max size =

[venus]
   path = /opt/venus
   inherit permissions = no
   read only = no
   valid users = timemachine
   vfs objects = acl_xattr fruit streams_xattr
   fruit:time machine = yes
   fruit:time machine max size =
```

If this resolved your issue, can you please close this ticket?

Regards,
 Hollie

**Comment by mbentley** [comment]
Closing to try to clean up open issues.  Please comment or reopen if you still have issues.
