### ISSUE TITLE
'Network backup disk cannot be accessed' with default config

### ISSUE THREAD

**Issue by KevinAstoria** [mbentley/docker-timemachine#75]
Hi,

We're currently running into some trouble getting TimeMachine to backup to a remote Linux (CentOS8) server, specifically the errors below: 
`The network backup disk could not be accessed because there was a problem with the network username or password. You may need to re-select the backup disk and enter the correct username and password.` --> From TimeMachine itself
and 
`Failed to fetch record!
pcap cache not loaded
error in mds_init_ctx for: /opt/timemachine
_mdssvc_open: Couldn't create policy handle for timemachine` in the logs of the timemachine Docker container. Those last two lines repeat each time we try to backup from TimeMachine.

* All config is kept default (without Avahi discovery); User/pw should both be 'timemachine'
* We can connect to the share with cmd+K in Finder (using timemachine/timemachine)
* Error happens when TimeMachine tries to backup
* Due to some company VPN & firewall stuff, we're connecting to the SMB port on the remote Linux server using ssh -L from a Mac (possible cause?)

We've checked whether permissions on the server are setup right (they seem to be), and searching the particular errors separately on SMB questions/fora does not seem to get us tangible results or leads to debug further. Does anyone have an idea what we're running into here?

**Comment by mbentley** [comment]
Sorry I haven't been able to look into this yet.  I'll have to see if this is something I can replicate at all but it will probably take some time.  What version of macOS are you running?

**Comment by tdspencer3** [comment]
I am pretty sure the mds messages/errors are from spotlight, which is not enabled in this image. TimeMachine will try to use Spotlight to index the backup, but it doesn't appear TimeMachine requires it and still works fine without it.

**Comment by mbentley** [comment]
While not fully relevant to the issue, I was curious if it would be useful to have spotlight indexing work to speed up the time machine process and was thinking about doing some sort of proof of concept to test it but even just for a quick and dirty POC, it looked like a bit of a pain in the ass to be honest.  Actually getting it properly working in a seamless fashion probably wouldn't happen without a decent amount of research and testing so that's probably not going to happen unless someone either would help with that or could prove that it would be a significant performance increase.

Now for the actual issue, I figured I would try it super quickly and I end up with the same issue.  What port are you attempting to map back via port forwarding over ssh?  Is it using the default port of 445 or are you using a different port?  I tried with 4450 and like you, I can connect to the share fine but timemachine doesn't work.  I also reconfigured timemachine to actually use port 4450 but it also didn't work.

<img width="1330" alt="screenshot 2021-01-22 at 7 19 53 PM" src="https://user-images.githubusercontent.com/414445/105562133-0837af80-5ce7-11eb-9e0c-0eedf08bab13.png">

So I am not sure if it is something there it doesn't work natively either when tunneling over ssh or a specific config issue related to the container but it's difficult to say since it works fine for normal use cases.

**Comment by tdspencer3** [comment]
I also briefly looked into what it would take to get spotlight working. I also felt the same way about it. Maybe some day...

**Comment by mundschenk-at** [comment]
@mbentley What issue are you having with Spotlight? I am currently using another image (https://github.com/awlx/samba-timemachine which seems to work fine regarding spotlight) but want to switch to yours for the "native" multi-user support. I'd be willing to help work this out.

**Comment by mbentley** [comment]
It's only for spotlight indexing.  the `awlx` image doesn't appear to do anything specific related to running any additional processes to allow for spotlight indexing.

**Comment by mundschenk-at** [comment]
> It's only for spotlight indexing. the `awlx` image doesn't appear to do anything specific related to running any additional processes to allow for spotlight indexing.

Oh, OK, it only includes [`spotlight = yes` in its `smb.conf`](https://github.com/awlx/samba-timemachine/blob/main/samba.conf#L30). From the initial information in the Samba wiki, I thought that this was enough, but (together with setting the backend to `elasticsearch`), but yeah, so there would need to be an installation of `elasticsearch` and `fscrawler` as well.

**Comment by benny1213** [comment]
> default port of 445

i also tried the port different than 445 and it's shows same Auth failure on system log, while once i tried 445 port, timemachine backup just fine without anyother config changing. 

but i am wondering why we can't use port other than 445 and if there is other way to work though, cause my ISP block 80/443 as well as 445 ports.

**Comment by mbentley** [comment]
> > default port of 445
> 
> 
> 
> i also tried the port different than 445 and it's shows same Auth failure on system log, while once i tried 445 port, timemachine backup just fine without anyother config changing. 
> 

Did you make sure to specify the port when trying to connect to the time machine?


> but i am wondering why we can't use port other than 445 and if there is other way to work though, cause my ISP block 80/443 as well as 445 ports.

You can change it. Your ISP isn't blocking the port unless they're actively filtering your private network or you're trying to connect over the internet through your router which would be a terrible idea.

**Comment by benny1213** [comment]
thanks for replying @mbentley 

> Did you make sure to specify the port when trying to connect to the time machine?

yes i did, i can connect to my samba server with specific port using Finder App but not using TimeMachine App.

> you're trying to connect over the internet through your router which would be a terrible idea.

yes, i am trying to connect over the internet, i think it would be much more convenient when i am not home. is it not secure doing that? i think there is a username/password protection and it would be fine.

> Your ISP isn't blocking the port

i think my ISP is, i used to try nmap my router IP from a different network (mobile hotspot), which shows 80/443/445 is off wile i had some service on those port.

**Comment by mbentley** [comment]
If you really want to backup when you're not at home, you should make use of a VPN.  I would never recommend exposing Samba on a public interface, authentication or not.

**Comment by benny1213** [comment]
sure, will use a VPN then, thank you @mbentley
