### ISSUE TITLE
Use proper tags for docker images

### ISSUE THREAD

**Issue by bkupidura** [mbentley/docker-timemachine#94]
**Is your feature request related to a problem? Please describe.**
Currently tags used by mbentley/docker-timemachine are 'fixed' (`smb`, `latest`, `afp`). This can lead to some inconsistency   - `latest` today is differ than `latest` from 2 week ago. 

When deploying `mbentley/timemachine` i need to download image everytime to be sure that `latest` is really `latest` (`imagePullPolicy: Always`).

Moreover users dosent have any control about which container version they are running. If i find out that `latest` is somehow broken, how i can revert to previous image?

Of course i can use container hash, but its not very user friendly.

**Describe the solution you'd like**
Just use proper versioning with increamenting version after each build.
I suggest to start with schema like: `protocol-samba-version.container_build_number` e.g `smb-4.14.5.0` -> `smb-4.14.5.1` -> ... -> `smb-4.14.5.50`
But honestly any schema will be better than `latest` and `smb` :)

**Comment by mbentley** [comment]
Previously when I was using Docker Hub for auto-builds, I didn't have much control over how the images were tagged due to some limitations in the autobuilds.  Now that I build images on my own CI server, I have full control over that so it would be possible to do something. In addition to that, I don't really put in any additional effort unless I personally find the need to do so.  The exception to that being in situations where I find out that many people are using an image of mine and this is certainly one of those cases.

I don't have any intentions on changing anything about the current tags available but I am open to adding additional tags.  There is basically no way I am going to be able to do build numbers though.  I rebuild images daily using buildkit (via buildx) and they're typically cached but sometimes buildkit will randomly decide the cache is missed.  The logic to check to see if an image has changed would be less than ideal and probably a bit brittle.  Locking in on a digest is indeed basically the only way to guarantee an image doesn't change because of my personal policy of how I build and ship images that I will describe next in a bit more detail.

The reason I trigger builds daily of all of my images across all of my repos is that it barely takes any resources to do so, assuming that the cache hasn't been busted.  Reasons why the cache would be busted would be a git repo change, a base image update, buildkit cache randomly busting or me forcing a rebuild.  Now here comes the tricky part - I never want to publish an image tag that will go stale.  By stale, I mean that I absolutely do not want to build an image, push it, and never update it again.  This could lead to someone running a container with a vulnerability in it and it would never get patched.  So in order to be able to have reproducible builds, I need to be able to have predictable image tags.  If the tags aren't something I can essentially hard code and put into a build job, I would rather not do it.

The only real solution that I would see to this problem would be to build images and tag the images with the version of the base OS image as with Alpine Linux, they tend to keep the packages the same version between a given version, meaning that something should not break between rebuilds.  So I could do something like:

```
smb-latest (also tagged to `smb`, `latest`, and `smb-3.14`)
smb-3.13
smb-3.12
smb-3.11
```

This would provide the following versions of Samba:
```
smb-3.14 - 4.14.x 
smb-3.13 - 4.13.x
smb-3.12 - 4.12.x
smb-3.11 - 4.11.x
```

That still leaves a lot of images to build once you also factor in `armv7l` and `arm64` but it could be possible.  I do not intend on changing any behavior of the `afp` images - those are deprecated.  Of course, I can do whatever variation I want on the tags if that's not clear as I can see how it would be confusing.

Now I could *probably* do tags with the `samba-server` package version but I would have to verify that the package was indeed the right package version (e.g. - tags like `smb-4.14`, `smb-4.13`, etc) but I would not do bugfix version tags as I don't believe there is a good reason to run a specific bugfix version.  If something _does_ break, I will fix it but it is not worth my time to otherwise maintain a lot of tags for what I perceive to be next to no gain.

Let me know your thoughts on any of the above to see if there is any possible solution in there that might help solve the issue you described or what might work best from your point of view.

**Comment by bkupidura** [comment]
Thans for clarifying build process of yours docker images!

To be clear, probably most users (all of them?) are not really interested what version of samba is running inside container. I suggested that as this is "biggest" part of this image.  

My second idea was to tag images based on build date, e.g smb-20200728 (ubuntu is using this schema). But if you are building images daily, its possible that 2 images with different tag will have exactly same content. Im not sure if docker hub (or buildkit) have any method to ignore image push when only tag changed (probably no). 

Regarding "stale" images, i believe that if somebody is using docker, he is aware that he needs to update. So i dont see issue here (except planty of tags after some time).

Suggested tag based on base image version, will also work. Its not perfect (still smb-3.14 can have different content than smb-3.14 pulled 2 weeks ago). But its step in good direction. As i said, any tag which changes over time will be better than fixed `latest` or `smb`.

**Comment by mbentley** [comment]
Ideally I would love it if the image tags represented the version of the software that was inside of the image.  In fact, I have seen most software specifically do this.  I see this often where if the version of a package is `3.14.1`, there will be a major tag (`3`), a major.minor tag (`3.14`) and also a major.minor.bugfix tag (`3.14.1`) so that a user can pick what they want to use. 
 That being said, they also build images once and never patch them again which is something I am not really wanting to do.  It would also be more complicated to do as buildkit never loads the images into Docker directly and I would have to do that in order to get the samba version number from inside the built container as I wouldn't know the version otherwise.

Another project I have a Docker image for, I only provide tags for the major version but that is mostly because the minor versions don't stick around for long.   It's my [Universal Media Server](https://github.com/mbentley/docker-ums#multi-arch-tags) image and it works well but I also get the software from GitHub and not the OS package repos so I know what version is going to be installed because of GitHub releases because I have to request the version as a part of the image build.

When it comes to pushing an image where the content is identical to another image that already exists, the only thing written to the registry is the image manifest - the layers would be identical if nothing changed so there would indeed be many image tags with the exact same content and just different tags.  Writing a new manifest is actually very easy.  For example, here is how the `smb` tag is created:

```
docker manifest create mbentley/timemachine:smb --amend mbentley/timemachine:smb-amd64 --amend mbentley/timemachine:smb-armv7l --amend mbentley/timemachine:smb-arm64
docker manifest push mbentley/timemachine:smb
```

I could create the additional tag by just creating and pushing a new manifest:
```
docker manifest create mbentley/timemachine:smb-$(date +%Y%m%d) --amend mbentley/timemachine:smb-amd64 --amend mbentley/timemachine:smb-armv7l --amend mbentley/timemachine:smb-arm64
docker manifest push mbentley/timemachine:smb-$(date +%Y%m%d)
```

It wouldn't even involve a new image build as the image is already being built.  It's just a different tag.

**Comment by bkupidura** [comment]
So this is great, only issue i can see currently that after some time you will have **plenty** of tags. But this not technical issue.

Unfortunately i dont see anything in dockerhub which allows you to automatically remove old tags (e.g remove tags older than N months).

**Comment by mbentley** [comment]
Now this part could be a little annoying but doable.  I could just assume that I want to keep tags around for `n` months, say 6 months and I can easily get the date from 6 months ago using `date --date='-6 months' +%Y%m%d`.

```
# get a token
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "<username>", "password": "<password>"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

# hit the delete endpoint, passing the token
curl -H "Authorization: JWT ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags/smb-$(date --date='-6 months' +%Y%m%d)/"
```

**Comment by bkupidura** [comment]
I would suggest to firstly fetch all tags and after that localy iterate over them and remove older than N.

If you will remove only tag $(today-6months), and smth bad happend with host where you are running that (hardware issue, cron issue, network outage, ...) you will need manualy remove tags which should be removed during downtime window.

**Comment by mbentley** [comment]
Yeah, I was just being lazy - getting tags from Docker Hub just kinda sucks, especially since there isn't really a well documented API.

**Comment by bkupidura** [comment]
```
#!/bin/bash
NOW=$(date +%s)
VALID_FOR_SEC=$((6*24*60*60))
while read TAG_NAME TAG_LAST_PUSHED; do
    TAG_LAST_PUSHED_SEC=$(date -j -f '%Y-%m-%dT%T' ${TAG_LAST_PUSHED} +%s 2> /dev/null)
    DIFF=$(( ${NOW} - ${TAG_LAST_PUSHED_SEC} ))
    if [ ${DIFF} -gt ${VALID_FOR_SEC} ]; then
        echo "removing tag ${TAG_NAME}"
    else
        echo "tag age ${DIFF}, threshold ${VALID_FOR_SEC} - not removing"
    fi
done < <(curl -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags" | jq -r '.results[] | .name + " " + .tag_last_pushed')
```

**Comment by mbentley** [comment]
Thanks for that.  Luckily a script I wrote a long time ago that migrated repos from Docker Hub to a v2 registry still exists.

https://github.com/docker-archive/migrator/blob/master/migrator.sh#L603-L623

```
      # reset the IMAGE_TAGS variable
      IMAGE_TAGS=""

      # set page URL to start with
      PAGE_URL="https://hub.docker.com/v2/repositories/${NAMESPACE}/${i}/tags/?page=1&page_size=250"

      # retrieve a list of tags at the target repository
      TAGS_AT_TARGET=$(query_tags_to_skip ${NAMESPACE}/${i})

      # loop through each page of tags
      while [ "${PAGE_URL}" != "null" ]
      do
        # get a list of tags on this page
        PAGE_DATA=$(curl ${INSECURE_CURL} -sf -H "Authorization: JWT ${TOKEN}" "${PAGE_URL}") || catch_error "curl => API failure getting tag list"

        # figure out next page URL
        PAGE_URL="$(echo $PAGE_DATA  | jq -r .next)"

        # Add tags to the list
        IMAGE_TAGS="${IMAGE_TAGS} $(echo ${PAGE_DATA} | jq -r '.results|.[]|.name')"
      done
```

**Comment by mbentley** [comment]
Hmm, there is something off in the logic.  I did some tweaking to just only do a single tag:

```
#!/bin/bash

set -x

NOW=$(date +%s)
VALID_FOR_SEC=$((6*24*60*60))

while read -r TAG_NAME TAG_LAST_PUSHED; do
  TAG_LAST_PUSHED_SEC=$(date -j -f '%Y-%m-%dT%T' "${TAG_LAST_PUSHED}" +%s 2> /dev/null)
  DIFF=$(( NOW - TAG_LAST_PUSHED_SEC ))
  if [ ${DIFF} -gt ${VALID_FOR_SEC} ]; then
    echo "removing tag ${TAG_NAME}"
  else
    echo "tag age ${DIFF}, threshold ${VALID_FOR_SEC} - not removing"
  fi
done < <(curl -s "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags?page=1&page_size=1" | jq -r '.results[] | .name + " " + .tag_last_pushed')
```

```
$ bash hub_tags.sh
++ date +%s
+ NOW=1627570430
+ VALID_FOR_SEC=518400
+ read -r TAG_NAME TAG_LAST_PUSHED
++ curl -s 'https://hub.docker.com/v2/repositories/mbentley/timemachine/tags?page=1&page_size=1'
++ jq -r '.results[] | .name + " " + .tag_last_pushed'
++ date -j -f %Y-%m-%dT%T 2021-07-29T07:05:12.135768Z +%s
+ TAG_LAST_PUSHED_SEC=
+ DIFF=1627570430
+ '[' 1627570430 -gt 518400 ']'
+ echo 'removing tag latest'
removing tag latest
+ read -r TAG_NAME TAG_LAST_PUSHED
```

**Comment by mbentley** [comment]
I took your concept and simplified a few things:

```
#!/bin/bash

PURGE_DATE="$(date --date='-6 months' +%s)"

while read -r TAG_NAME TAG_LAST_PUSHED; do
  TAG_LAST_PUSHED_SEC=$(date -d "${TAG_LAST_PUSHED}" +%s)
  if [ "${TAG_LAST_PUSHED_SEC}" -lt "${PURGE_DATE}" ]; then
    echo "tag age $(date -d "@${TAG_LAST_PUSHED_SEC}" +%Y-%m-%d), threshold $(date -d "@${PURGE_DATE}" +%Y-%m-%d), ${TAG_NAME}, removing"
  else
    echo "tag age $(date -d "@${TAG_LAST_PUSHED_SEC}" +%Y-%m-%d), threshold $(date -d "@${PURGE_DATE}" +%Y-%m-%d), ${TAG_NAME}, NOT removing"
  fi
done < <(curl -s "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags?page=1&page_size=10000" | jq -r '.results[] | .name + " " + .tag_last_pushed')
```

Setting it to 1 month (which I have tags old enough in the repo), it shows that it catches tags:

```
$ bash hub_tags.sh
tag age 2021-07-29, threshold 2021-06-29, latest, NOT removing
tag age 2021-07-29, threshold 2021-06-29, smb, NOT removing
tag age 2021-07-28, threshold 2021-06-29, smb-20210728, NOT removing
tag age 2021-07-18, threshold 2021-06-29, latest-smb-armv7l, NOT removing
tag age 2021-07-18, threshold 2021-06-29, smb-armv7l, NOT removing
tag age 2021-07-14, threshold 2021-06-29, latest-smb-amd64, NOT removing
tag age 2021-07-14, threshold 2021-06-29, smb-amd64, NOT removing
tag age 2021-07-13, threshold 2021-06-29, afp-amd64, NOT removing
tag age 2021-07-13, threshold 2021-06-29, latest-smb-arm64, NOT removing
tag age 2021-06-25, threshold 2021-06-29, afp, removing
tag age 2021-06-25, threshold 2021-06-29, smb-arm64, removing
```

I can probably add a whitelist for tags that I want it to never remove for cases of old or legacy tags.

**Comment by mbentley** [comment]
Here is a full script:

```
#!/bin/bash

# get the date, in seconds, for when we should purge tags before
PURGE_DATE="$(date --date='-6 months' +%s)"

# get Docker Hub credentials
HUB_AUTH="$(jq -r '.auths."https://index.docker.io/v1/".auth' "${HOME}/.docker/config.json" | base64 -d)"

# make sure we received credentials
if [ -z "${HUB_AUTH}" ]
then
  echo "ERROR: authorization data not found (have you performed a \"docker login\")?"
  exit 1
else
  # get a token
  TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$(echo "${HUB_AUTH}" | awk -F ':' '{print $1}')"'", "password": "'"$(echo "${HUB_AUTH}" | awk -F ':' '{print $2}')"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
fi

# initialize default loop variables
TAG_PAGE="1"
NEXT_PAGE=""

while [ "${NEXT_PAGE}" != "null" ]
do
  # get a page of tags
  PAGE_OF_TAGS="$(curl -s -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags?page=${TAG_PAGE}&page_size=50")"

  # set the next page variable
  NEXT_PAGE="$(echo "${PAGE_OF_TAGS}" | jq -r .next)"

  # add the tags from the page to the list of tags
  HUB_TAGS="${HUB_TAGS}
$(echo "${PAGE_OF_TAGS}" | jq -r '.results[] | .name + " " + .tag_last_pushed')"

  # increment the tag page
  TAG_PAGE=$((TAG_PAGE+1))
done

# trim off any blank lines from the list of tags
HUB_TAGS="$(echo "${HUB_TAGS}" | sed '/^[[:space:]]*$/d')"

while read -r TAG_NAME TAG_LAST_PUSHED
do
  # check to see if we should skip the tag
  if echo "${TAG_NAME}" | grep -qE '(^latest$)|(^afp$)|(^smb$)|(-arm64$)|(-amd64$)|(-armv7l$)'
  then
    echo "skip tag ${TAG_NAME}"
  else
    # convert the date to seconds
    TAG_LAST_PUSHED_SEC=$(date -d "${TAG_LAST_PUSHED}" +%s)

    # compare the tag last pushed date to the purge date cutoff
    if [ "${TAG_LAST_PUSHED_SEC}" -lt "${PURGE_DATE}" ]
    then
      # purge tag
      echo "tag age $(date -d "@${TAG_LAST_PUSHED_SEC}" +%Y-%m-%d), threshold $(date -d "@${PURGE_DATE}" +%Y-%m-%d), ${TAG_NAME}, removing"

      # delete the tag
      curl -H "Authorization: JWT ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/mbentley/timemachine/tags/${TAG_NAME}/"
    else
      # do not purge tag
      echo "tag age $(date -d "@${TAG_LAST_PUSHED_SEC}" +%Y-%m-%d), threshold $(date -d "@${PURGE_DATE}" +%Y-%m-%d), ${TAG_NAME}, NOT removing"
    fi
  fi
done < <(echo "${HUB_TAGS}")
```

**Comment by mbentley** [comment]
Let me go ahead and add the manifest creation and I will get to the delete script later - after all, I won't need it for a while :)

**Comment by bkupidura** [comment]
Thanks! I believe that not only me will be happy with that change :)

**Comment by mbentley** [comment]
OK, I now have a `smb-20210730` image tag that is was just published.

**Comment by mbentley** [comment]
OK, everything is in place.  I just need to update the README.

```
 + ./util/prune_hub_tags.sh
 skip tag latest-smb-arm64
 skip tag latest-smb-amd64
 skip tag afp
 skip tag afp-amd64
 skip tag smb-armv7l
 skip tag smb-amd64
 skip tag smb-arm64
 skip tag latest-smb-armv7l
 skip tag smb
 tag age 2021-07-30, threshold 2021-01-30, smb-20210730, NOT removing
 skip tag latest
```

**Comment by mbentley** [comment]
README has been updated.
